name: yt_cors_proxy
description: A YouTube CORS Proxy Server.
version: 1.0.0

environment:
  sdk: '>=2.19.0-444.4.beta <3.0.0'

dependencies:
  http: ^0.13.5
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.4

dev_dependencies:
  lints: ^2.0.0
