name: startup_namer
description: A startup-namer app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-0 <3.0.0"

# #docregion dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
# #enddocregion dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
