name: firebase_backend_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  googleapis: ">=9.2.0 <11.0.0"
  googleapis_auth: ^1.3.0
  http: ^0.13.4
  shelf: ^1.3.0
  shelf_router: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
