version: 2
enable-beta-ecosystems: true
updates:
  # Github actions ecosystem.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      # Don't auto-submit github action updates until subosito/flutter-action update is cleared
      # - "autosubmit"
  # Pip ecosystem.
  - package-ecosystem: "pip"
    directory: "/tfagents-flutter/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  # Pub ecosystem.
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/adaptive_app/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/animated-responsive-layout/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/animations/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/audio_soloud/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/boring_to_beautiful/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/brick_breaker/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/colorist/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/dart-patterns-and-records/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/deeplink_cookbook/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/ffigen_codelab/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/firebase-auth-flutterfire-ui/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/firebase-emulator-suite/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/firebase-get-to-know-flutter/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/forge2d_game/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/generate_crossword/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/github-client/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/google-maps-in-flutter/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/haiku_generator/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/homescreen_codelab/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/in_app_purchases/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/intro_flutter_gpu/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/namer/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/next-gen-ui/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/testing_codelab/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/tfagents-flutter/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/tfrs-flutter/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/tfserving-flutter/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/tooling/codelab_rebuild/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/webview_flutter/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
