name: myartist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  adaptive_breakpoints: ^0.1.4
  adaptive_components: ^0.0.7
  adaptive_navigation: ^0.0.7
  animations: ^2.0.4
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  desktop_window: ^0.4.0
  dynamic_color: ^1.5.3
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  go_router: ^4.3.0
  google_fonts: ^3.0.1
  material_color_utilities: ^0.1.5
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/
