name: myartist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  adaptive_breakpoints: ^0.1.6
  adaptive_components: ^0.0.9
  adaptive_navigation: ^0.0.9
  animations: ^2.0.7
  collection: ^1.17.0
  cupertino_icons: ^1.0.5
  desktop_window: ^0.4.0
  dynamic_color: ^1.6.2
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  material_color_utilities: ^0.2.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/
