# Copyright 2020 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: testing_app
description: App behind Flutter testing codelab.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  provider: ^6.0.1

dev_dependencies:
  flutter_driver: # new
    sdk: flutter # new
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test: # new
    sdk: flutter # news
  test: ^1.17.12

flutter:
  uses-material-design: true
