name: yt_cors_proxy
description: A YouTube CORS Proxy Server.
version: 1.0.0

environment:
  sdk: ^3.1.0-0

dependencies:
  http: ^1.1.0
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^2.0.0
