name: yt_cors_proxy
description: A YouTube CORS Proxy Server.
version: 1.0.0

environment:
  sdk: ^3.8.0-0

dependencies:
  shelf: ^1.4.0
  http: ^1.4.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^6.0.0
