name: yt_cors_proxy
description: A YouTube CORS Proxy Server.
version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  http: ^0.13.4
  shelf: ^1.1.0
  shelf_cors_headers: ^0.1.2

dev_dependencies:
  lints: ^1.0.0
