name: complete
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth_google: ^1.3.3
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
