name: complete
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutterfire_ui: ^0.4.3+20
  google_sign_in: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
