name: myartist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.0-0

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.1.7
  adaptive_components: ^0.0.10
  adaptive_navigation: ^0.0.10
  animations: ^2.0.11
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  desktop_window: ^0.4.0
  dynamic_color: ^1.7.0
  english_words: ^4.0.0
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  material_color_utilities: any
  universal_platform: ^1.1.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/
