name: startup_namer
description: A startup-namer app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
