name: codelab_rebuild
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies: 
  checked_yaml: ^2.0.1
  cli_script: ^0.2.4
  io: ^1.0.3
  json_annotation: ^4.4.0
  logging: ^1.0.2
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  lints: ^2.0.0
  test: ^1.16.0
