name: dashclicker
description: A codelab for in-app purchases
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  google_sign_in: ^7.2.0
  http: ^1.6.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  logging: ^1.3.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  in_app_purchase_platform_interface: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
