name: quiz
description: "A quiz app for demonstrating animation effects in Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-0

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
