name: generate_crossword
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-0

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.1.1
  built_value: ^8.12.0
  characters: ^1.4.0
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  two_dimensional_scrollables: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  built_value_generator: ^8.12.0
  custom_lint: ^0.8.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
