name: complete
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-417.3.beta <4.0.0'

dependencies:
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.2.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutterfire_ui: ^0.4.3+20
  google_sign_in: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
