name: dashclicker
description: A codelab for in-app purchases
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  http: ^1.4.0
  intl: ^0.20.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
