name: dashclicker
description: A codelab for in-app purchases
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.1
  cloud_functions: ^4.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.0
  in_app_purchase: ^3.0.4
  intl: ^0.18.0
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
