name: dashclicker
description: A codelab for in-app purchases
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  google_sign_in: ^7.2.0
  http: ^1.6.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
