name: dashclicker
description: A codelab for in-app purchases
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  google_sign_in: ^6.2.2
  http: ^1.3.0
  intl: ^0.20.2
  provider: ^6.1.2
  in_app_purchase: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  in_app_purchase_platform_interface: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
