name: myartist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^2.17.0-0
dependencies:
  adaptive_breakpoints: ^0.0.4
  adaptive_components: ^0.0.3
  adaptive_navigation: ^0.0.5
  animations: ^2.0.2
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.1.2
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  go_router: ^3.0.1
  google_fonts: ^2.3.1
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/
