name: flutter_cookbook
description: Source project for the design examples in the Flutter cookbook.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0

flutter:
  uses-material-design: true
