name: myartist
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  desktop_window: ^0.4.2
  dynamic_color: ^1.7.0
  english_words: ^4.0.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  material_color_utilities: any
  universal_platform: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/
