name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

defaults:
  run:
    shell: bash

# Declare default permissions as read only.
permissions: read-all

jobs:
  test:
    name: Test Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        flutter_version: [stable, beta, master]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8
        with:
          distribution: 'zulu' # See https://github.com/actions/setup-java#supported-distributions
          java-version: "17"
      - uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
        with:
          channel: ${{ matrix.flutter_version }}
      - run: dart --version
      - run: flutter --version
      - run: ./flutter_ci_script_${{ matrix.flutter_version }}.sh
